language: go

go:
- 1.5.x
- 1.6.x
- 1.7.x
- 1.8.x
- 1.9.x
- 1.x
- master

matrix:
  allow_failures:
  - go: master
  fast_finish: true

sudo: false

before_install:
- wget -q -O dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
- chmod +x dep && mv dep "${GOPATH}"/bin
- go get github.com/mattn/goveralls
- export GO_TEST_COVERAGE_FILENAME='coverage.out'
- export GO15VENDOREXPERIMENT=1

install:
- make cmd-deps-local

script:
- make test-with-coverage-profile ARGS='-timeout=1s'

after_success:
- goveralls -service=travis-ci -coverprofile="${GO_TEST_COVERAGE_FILENAME}"
- echo $TRAVIS_GO_VERSION ":" $TRAVIS_TAG
- if [[ $TRAVIS_GO_VERSION == 1.9* ]] && [ -n "$TRAVIS_TAG" ]; then curl -sL https://git.io/goreleaser | bash; fi

notifications:
  slack: octolab:1eMS7IqOArBipiu31jYVd0cN
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/63f69d732d88862909a2
    on_success: change
    on_failure: always
    on_start:   never
