language: go

go:
- 1.5
- 1.6
- 1.7
- 1.8
- tip

sudo: false

before_install:
- go get github.com/mattn/goveralls
- export GO_TEST_COVERAGE_FILENAME='coverage.out'

install:
- make install-deps
- make build

script:
- make test-with-coverage-profile OPEN_BROWSER=

after_success:
- goveralls -service=travis-ci -coverprofile="${GO_TEST_COVERAGE_FILENAME}"

matrix:
  allow_failures:
  - go: tip
  fast_finish: true

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/f59d6c6f7dc08e96aa85
    on_success: change
    on_failure: always
    on_start: never
